######################################################################
# Automatically generated by qmake (3.0) ven. avr. 7 17:00:37 2017
######################################################################

QT += widgets
TEMPLATE = app
TARGET = guinix
INCLUDEPATH += .

# Input
HEADERS += fenetre.h
SOURCES += fenetre.cpp main.cpp
